const {chromium}=require('playwright');
const fs=require('fs'),path=require('path');
(async()=>{
 fs.mkdirSync('test-results',{recursive:true});const b=await chromium.launch({headless:true});const p=await b.newPage({viewport:{width:1500,height:1100},acceptDownloads:true});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('file:///'+path.resolve('index.html').replaceAll('\\','/'));await p.waitForFunction(()=>document.querySelector('#status').textContent==='Ready to export',null,{timeout:15000});
 const ids=await p.locator('[data-layout]').evaluateAll(bs=>bs.map(b=>b.dataset.layout));let count=0;
 async function assertSafe(label){const r=await p.locator('#canvas').evaluate(c=>({warnings:c._warnings,bad:c._layoutBoxes.filter(t=>t.x<c._safe.x-.5||t.y<c._safe.y-.5||t.x+t.w>c._safe.x+c._safe.w+.5||t.y+t.h>c._safe.y+c._safe.h+.5)}));if(r.warnings.length||r.bad.length)throw Error(label+': '+JSON.stringify(r));count++}
 for(const id of ids){await p.locator(`[data-layout="${id}"]`).click();for(const format of ['portrait','square','story']){await p.selectOption('#format',format);await assertSafe(id+'/'+format);await p.selectOption('#scale','0.85');await assertSafe(id+'/'+format+'/smaller');await p.selectOption('#scale','1.12');await p.fill('#footer','Speak with your clinician about your care. Individual circumstances vary.');await assertSafe(id+'/'+format+'/larger+disclosure');await p.fill('#footer','');await p.selectOption('#scale','1');}await p.selectOption('#format','portrait');}
 // Verify guides never alter the export pixels.
 await p.locator('[data-layout="editorial"]').click();const before=await p.locator('#canvas').evaluate(c=>c.toDataURL());await p.uncheck('#safeGuides');const after=await p.locator('#canvas').evaluate(c=>c.toDataURL());if(before!==after)throw Error('Guide affected artwork');await p.check('#safeGuides');const dl=p.waitForEvent('download');await p.click('#export');await(await dl).saveAs('test-results/guide-export.png');if(fs.readFileSync('test-results/guide-export.png').toString('base64')!==before.split(',')[1])throw Error('Export differs from clean canvas');
 await p.fill('#headline','A saved reminder');await p.locator('[data-layout="question"]').click();await p.locator('[data-layout="editorial"]').click();if(await p.inputValue('#headline')!=='A saved reminder')throw Error('Draft lost');const sd=p.waitForEvent('download');await p.click('#save');await(await sd).saveAs('test-results/v3-project.json');await p.click('#reset');await p.setInputFiles('#project','test-results/v3-project.json');await p.waitForFunction(()=>document.querySelector('#headline').value==='A saved reminder');await p.click('#reset');
 // Too many list items are visible as an actionable error and cannot be silently exported.
 await p.locator('[data-layout="number"]').click();await p.fill('#benefits','One|Two|Three|Four');await p.click('#export');if(!(await p.locator('#toast').textContent()).includes('Shorten'))throw Error('Invalid list exported');await p.click('#reset');
 await p.setInputFiles('#upload','assets/campaigns/mwc-250-slide-2.jpg');await p.waitForFunction(()=>document.querySelector('#toast').textContent==='Your supplied photo is ready.');await p.click('#reset');
 fs.mkdirSync('test-results/template-exports',{recursive:true});for(const id of ids){await p.locator(`[data-layout="${id}"]`).click();await p.click('#reset');const url=await p.locator('#canvas').evaluate(c=>c.toDataURL());fs.writeFileSync('test-results/template-exports/MWC-'+id+'.png',Buffer.from(url.split(',')[1],'base64'));}
 await p.click('#gridView');const gd=p.waitForEvent('download');await p.click('#export');await(await gd).saveAs('test-results/template-grid.png');await p.screenshot({path:'test-results/v3-final-ui.png',fullPage:true});await p.locator('#collection button').first().click();await p.selectOption('#format','story');await p.screenshot({path:'test-results/v3-story-guide.png',fullPage:true});await p.setViewportSize({width:390,height:844});if(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');await p.screenshot({path:'test-results/v3-mobile.png',fullPage:true});if(errors.length)throw Error(errors.join('\n'));console.log(`PASS: ${count} content-bound checks; 36 template/format combinations, large type+disclosures, guide-free exports, draft save/open, list validation, photo uploads, grid export and mobile width.`);await b.close();
})().catch(e=>{console.error(e);process.exit(1)});
